"""Add ViewHistory table for date-based view tracking

Revision ID: 002_add_view_history
Revises: e5a1ff17c8e1
Create Date: 2025-07-21 16:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_view_history'
down_revision = 'e5a1ff17c8e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ViewHistory テーブルを作成（日付別閲覧履歴追跡）
    op.create_table('view_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('knowledge_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # パフォーマンス向上のためのインデックスを作成
    # 1. 記事別閲覧数集計用（最重要）
    op.create_index('idx_view_history_knowledge_date', 'view_history', ['knowledge_id', 'viewed_at'])
    
    # 2. 重複チェック用（日別重複防止クエリ用）
    op.create_index('idx_view_history_user_knowledge_date', 'view_history', ['user_id', 'knowledge_id', 'viewed_at'])
    
    # 3. 期間別集計用（人気記事ページ用）
    op.create_index('idx_view_history_date_knowledge', 'view_history', ['viewed_at', 'knowledge_id'])
    
    # 既存テーブルのインデックス最適化
    # Like テーブルのパフォーマンス向上
    op.create_index('idx_like_knowledge_date', 'like', ['knowledge_id', 'created_at'])
    op.create_index('idx_like_date_knowledge', 'like', ['created_at', 'knowledge_id'])
    
    # Comment テーブルのパフォーマンス向上  
    op.create_index('idx_comment_knowledge_date', 'comment', ['knowledge_id', 'created_at'])
    op.create_index('idx_comment_date_knowledge', 'comment', ['created_at', 'knowledge_id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 追加したインデックスを削除
    op.drop_index('idx_comment_date_knowledge', table_name='comment')
    op.drop_index('idx_comment_knowledge_date', table_name='comment')
    op.drop_index('idx_like_date_knowledge', table_name='like')
    op.drop_index('idx_like_knowledge_date', table_name='like')
    
    # ViewHistory関連のインデックスを削除
    op.drop_index('idx_view_history_date_knowledge', table_name='view_history')
    op.drop_index('idx_view_history_user_knowledge_date', table_name='view_history')
    op.drop_index('idx_view_history_knowledge_date', table_name='view_history')
    op.drop_table('view_history')